// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD39QnqIHCH31uPHdQu8CKmlaNeJaJnzA8',
    appId: '1:1011358514899:web:9a9bde0f8ec112cfe79e26',
    messagingSenderId: '1011358514899',
    projectId: 'trabalho-flutter-f3b7c',
    authDomain: 'trabalho-flutter-f3b7c.firebaseapp.com',
    storageBucket: 'trabalho-flutter-f3b7c.appspot.com',
    measurementId: 'G-0VHXXWL9PD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD-LDVAn3oUjT0aYL-v981mTOGJbsE8GeI',
    appId: '1:1011358514899:android:75efa750d06d6bb9e79e26',
    messagingSenderId: '1011358514899',
    projectId: 'trabalho-flutter-f3b7c',
    storageBucket: 'trabalho-flutter-f3b7c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDAik-KWJGXED0lRn7uDRUNwvoIrxCCTw',
    appId: '1:1011358514899:ios:548f7a8ab1b5ad30e79e26',
    messagingSenderId: '1011358514899',
    projectId: 'trabalho-flutter-f3b7c',
    storageBucket: 'trabalho-flutter-f3b7c.appspot.com',
    iosClientId: '1011358514899-bh0saguspepb1ijeof3v5mif4k9cj779.apps.googleusercontent.com',
    iosBundleId: 'com.example.projeto',
  );
}
